version: "3"

services:

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    networks:
      - network
    volumes:
      - ./config/mysql:/etc/mysql/
      - ./db:/docker-entrypoint-initdb.d/

  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: ${RESTART}
    networks:
      - network

  web:
    image: magento-2.3-dev-web
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      context: ./web
      args:
        SSH_PSWD: ${SSH_PSWD}
    depends_on:
      - mysql
      - redis
    restart: ${RESTART}
    networks:
      - network
    volumes:
      - ./config/nginx:/etc/nginx/
      - ./config/php:/usr/local/etc/php/

networks:

  network:
    external:
      name: ${NETWORK}
