version: "3"

services:

  elasticsearch:
    image: elasticsearch:2.4.6
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    restart: ${RESTART}
    networks:
      - network

  kibana:
    image: kibana:6.8.6
    container_name: ${COMPOSE_PROJECT_NAME}_kibana
    depends_on:
      - elasticsearch
    restart: ${RESTART}
    environment:
      SERVER_NAME: ${COMPOSE_PROJECT_NAME}_kibana
      ELASTICSEARCH_URL: "http://${COMPOSE_PROJECT_NAME}_elasticsearch:9200"
    networks:
      - network

  mysql:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PSWD}
    networks:
      - network

  rabbitmq:
    image: magento-dev-rabbitmq
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    build:
      context: ./rabbitmq
    restart: ${RESTART}
    networks:
      - network

  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: ${RESTART}
    networks:
      - network

  varnish:
    image: magento-dev-varnish
    container_name: ${COMPOSE_PROJECT_NAME}_varnish
    build:
      context: ./varnish
    depends_on:
      - web
    restart: ${RESTART}
    environment:
      BACKEND_HOST: ${COMPOSE_PROJECT_NAME}_web
    networks:
      - network

  web:
    image: magento-2.2-dev-web
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build:
      context: ./web
      args:
        SSH_PSWD: ${SSH_PSWD}
    depends_on:
      - elasticsearch
      - mysql
      - rabbitmq
      - redis
    restart: ${RESTART}
    networks:
      - network

networks:

  network:
    external:
      name: ${NETWORK}
