#!/bin/sh

if [ ! -f /etc/varnish/init ]; then
  sed -i "s/    .host = \"127.0.0.1\";/    .host = \"${BACKEND_HOST}\";/g" /etc/varnish/default.vcl
  touch /etc/varnish/init
fi

/usr/sbin/varnishd -F -f /etc/varnish/default.vcl;